#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/../../.." && pwd)"
version="$(node -p "require('$repo_root/package.json').version")"
build_dir="${TMPDIR:-/tmp}/orchard-arch-build-$version-$$"
src_dir="$build_dir/src/orchard-$version"
payload_dir="$build_dir/src/system-electron"
pkgdir="$build_dir/pkg/orchard"
pkgrel="$(sed -n 's/^pkgrel=//p' "$script_dir/PKGBUILD")"
pkg_file="$script_dir/orchard-$version-$pkgrel-x86_64.pkg.tar.zst"

trap 'rm -rf "$build_dir"' EXIT
rm -rf "$build_dir"
mkdir -p "$build_dir/src" "$pkgdir"

tar \
  --exclude=.git \
  --exclude=node_modules \
  --exclude=release \
  --exclude=release-linux \
  --exclude=release-windows \
  --exclude=release-system-electron \
  --exclude='packaging/linux/arch/*.tar.gz' \
  --exclude='packaging/linux/arch/*.pkg.tar.*' \
  --exclude='packaging/linux/arch/pkg' \
  --exclude='packaging/linux/arch/src' \
  --transform "s,^,orchard-$version/," \
  -C "$repo_root" -czf "$build_dir/orchard-$version.tar.gz" .
tar -C "$build_dir/src" -xzf "$build_dir/orchard-$version.tar.gz"

cd "$src_dir"
npm ci --ignore-scripts
ELECTRON_SKIP_BINARY_DOWNLOAD=1 npm rebuild
if [[ -f dist/index.html ]]; then
  node scripts/package-system-electron.mjs \
    --electron-dist=/usr/lib/electron43 \
    --output="$payload_dir"
else
  npm run package:linux-system -- \
    --electron-dist=/usr/lib/electron43 \
    --output="$payload_dir"
fi

install -Dm644 "$payload_dir/app.asar" "$pkgdir/usr/lib/orchard/app.asar"
if [[ -d "$payload_dir/app.asar.unpacked" ]]; then
  mkdir -p "$pkgdir/usr/lib/orchard"
  cp -a "$payload_dir/app.asar.unpacked" "$pkgdir/usr/lib/orchard/app.asar.unpacked"
fi

install -Dm755 "$script_dir/orchard" "$pkgdir/usr/bin/orchard"
install -Dm644 "$repo_root/packaging/linux/common/dev.sfg.orchard.desktop" \
  "$pkgdir/usr/share/applications/dev.sfg.orchard.desktop"
install -Dm644 "$src_dir/build/icon.png" \
  "$pkgdir/usr/share/icons/hicolor/512x512/apps/dev.sfg.orchard.png"
install -Dm644 "$src_dir/LICENSE" "$pkgdir/usr/share/licenses/orchard/LICENSE"

builddate="$(date +%s)"
installed_size="$(du -sb "$pkgdir/usr" | awk '{ print $1 }')"
cat > "$pkgdir/.PKGINFO" <<PKGINFO
# Generated by Orchard packaging
pkgname = orchard
pkgbase = orchard
xdata = pkgtype=pkg
pkgver = $version-$pkgrel
pkgdesc = YouTube Music client backed by InnerTube
url = https://sfg545.dev/orchard
builddate = $builddate
packager = Unknown Packager
size = $installed_size
arch = x86_64
license = custom
depend = electron43
makedepend = nodejs
makedepend = npm
PKGINFO

(
  cd "$pkgdir"
  bsdtar --format=mtree \
    --options='!all,use-set,type,uid,gid,mode,time,size,sha256,link' \
    -cf - .PKGINFO usr | gzip -c > .MTREE
)

if printf '' | zstd --quiet --ultra -22 --stdout >/dev/null 2>&1; then
  zstd_level='--ultra -22'
else
  zstd_level='-19'
fi

rm -f "$script_dir"/orchard-"$version"-*.pkg.tar.*
echo "Compressing the Arch package with zstd $zstd_level."
(
  cd "$pkgdir"
  bsdtar --uid 0 --gid 0 --uname root --gname root -cf - .MTREE .PKGINFO usr
) | zstd --compress --threads=0 $zstd_level --stdout > "$pkg_file"

chmod 644 "$pkg_file"
ls -lh "$pkg_file"
