buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.10'
        classpath 'org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:2.4.10'
    }
}
