org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=768m
org.gradle.parallel=true
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
