/*
 * Copyright (C) 2026 SFG545
 *
 * This file is part of Orchard.
 *
 * Orchard is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Orchard is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Orchard. If not, see <https://www.gnu.org/licenses/>.
 */

// Built-in names used by the pinned YouTube.js strict initializer policy.
pub(super) fn builtin(name: &str) -> bool {
    matches!(
        name,
        "AbortController"
            | "AbortSignal"
            | "Array"
            | "ArrayBuffer"
            | "AsyncContext"
            | "Atomics"
            | "AudioContext"
            | "BigInt"
            | "BigInt64Array"
            | "BigUint64Array"
            | "Blob"
            | "Boolean"
            | "BroadcastChannel"
            | "Buffer"
            | "CanvasRenderingContext2D"
            | "clearImmediate"
            | "clearInterval"
            | "clearTimeout"
            | "confirm"
            | "console"
            | "Crypto"
            | "CustomEvent"
            | "DataView"
            | "Date"
            | "decodeURI"
            | "decodeURIComponent"
            | "document"
            | "Element"
            | "encodeURI"
            | "encodeURIComponent"
            | "Error"
            | "escape"
            | "eval"
            | "Event"
            | "EventTarget"
            | "fetch"
            | "File"
            | "FileReader"
            | "Float32Array"
            | "Float64Array"
            | "FormData"
            | "function"
            | "global"
            | "globalThis"
            | "hasOwnProperty"
            | "Headers"
            | "History"
            | "HTMLElement"
            | "HTMLCollection"
            | "IDBKeyRange"
            | "Infinity"
            | "Int16Array"
            | "Int32Array"
            | "Int8Array"
            | "Intl"
            | "IntersectionObserver"
            | "isFinite"
            | "isNaN"
            | "isPrototypeOf"
            | "JSON"
            | "location"
            | "log"
            | "Map"
            | "Math"
            | "MediaRecorder"
            | "MediaSource"
            | "MediaStream"
            | "MemberExpression"
            | "MutationObserver"
            | "NaN"
            | "navigator"
            | "Node"
            | "NodeList"
            | "Number"
            | "Object"
            | "OfflineAudioContext"
            | "parse"
            | "parseFloat"
            | "parseInt"
            | "Performance"
            | "process"
            | "Promise"
            | "prompt"
            | "prototype"
            | "Proxy"
            | "ReadableStream"
            | "Reflect"
            | "RegExp"
            | "requestAnimationFrame"
            | "requestIdleCallback"
            | "Request"
            | "Response"
            | "ResizeObserver"
            | "Screen"
            | "setImmediate"
            | "setInterval"
            | "setTimeout"
            | "SharedArrayBuffer"
            | "SharedWorker"
            | "SourceBuffer"
            | "split"
            | "String"
            | "stringify"
            | "structuredClone"
            | "SubtleCrypto"
            | "Symbol"
            | "TextDecoder"
            | "TextEncoder"
            | "this"
            | "toString"
            | "TransformStream"
            | "Uint16Array"
            | "Uint32Array"
            | "Uint8Array"
            | "Uint8ClampedArray"
            | "undefined"
            | "unescape"
            | "URL"
            | "URLSearchParams"
            | "valueOf"
            | "WeakMap"
            | "WeakSet"
            | "WebAssembly"
            | "WebGLRenderingContext"
            | "window"
            | "Worker"
            | "WritableStream"
            | "XMLHttpRequest"
            | "alert"
            | "arguments"
            | "atob"
            | "btoa"
            | "cancelAnimationFrame"
            | "cancelIdleCallback"
            | "queueMicrotask"
    )
}
