/*
 * Copyright (C) 2026 SFG545
 *
 * This file is part of Orchard.
 *
 * Orchard is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Orchard is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Orchard. If not, see <https://www.gnu.org/licenses/>.
 */

package dev.sfg.orchard.mobile.playback.smart

import dev.sfg.orchard.mobile.model.Track
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test

/** Expected results are regenerated by Node from desktop sources before every changed test build. */
class TransitionPlannerTest {
    @Test fun `Rhino and Node agree on every live field and native decision`() {
        for (case in desktopCases()) {
            val input = case.getJSONObject("input")
            assertJson(case.getJSONObject("live"), DesktopTransitionPlanner.invoke("live", input), case.getString("name"))
            val nativeInput = JSONObject(input.toString())
                .put("duration", maxOf(input.getDouble("duration"), input.getJSONObject("currentTrack").getDouble("durationSeconds")))
                .put("nextDuration", input.getJSONObject("nextTrack").getDouble("durationSeconds"))
            assertJson(case.getJSONObject("native"), DesktopTransitionPlanner.invoke("native", nativeInput), case.getString("name") + ".native")
        }
    }

    @Test fun `Kotlin adapter preserves desktop live cues guards and choreography`() {
        for (case in desktopCases()) {
            val input = case.getJSONObject("input")
            val expected = case.getJSONObject("live")
            val plan = mobilePlan(input)
            val name = case.getString("name")
            assertEquals(name, expected.getBoolean("shouldStart"), plan.shouldStart)
            assertEquals(name, expected.getBoolean("markerVisible"), plan.markerVisible)
            assertEquals(name, expected.getString("reason"), plan.reason)
            assertEquals(name, expected.number("transitionStart"), plan.transitionStart, 1e-9)
            assertEquals(name, expected.number("transitionEnd"), plan.transitionEnd, 1e-9)
            assertEquals(name, expected.number("fadeSeconds"), plan.fadeSeconds, 1e-9)
            assertEquals(name, expected.number("incomingCueTime"), plan.incomingCueTime, 1e-9)
            assertEquals(name, expected.number("incomingHandoffTime"), plan.incomingHandoffTime, 1e-9)
            assertEquals(name, expected.number("incomingPlaybackRate", 1.0), plan.incomingPlaybackRate, 1e-9)
            assertEquals(name, expected.optJSONObject("choreography")?.choreography(), plan.choreography)
            assertEquals(name, expected.strings("policyReasons"), plan.policyReasons)
            assertEquals(name, !expected.getBoolean("markerVisible"), plan.blocked)
            if (!expected.has("pairPlan")) assertNull(name, plan.nativePlan)
        }
    }

    @Test fun `selected shared plan is executed live with its exact clocks and rates`() {
        val source = mobilePlan(desktopCases().first().getJSONObject("input"))
        val selected = checkNotNull(source.nativePlan).copy(
            transitionStart = 100.0,
            transitionEnd = 110.0,
            overlapSeconds = 8.0,
            outgoingTempoRatio = 1.25,
            incomingTempoRatio = 0.9,
            incomingCueTime = 12.0,
            incomingResumeTime = 19.2,
            strategy = "filtered_blend",
            choreography = null,
        )
        val plan = source.copy(nativePlan = selected)

        val waiting = plan.forLivePlayback(99.0)
        assertFalse(waiting.shouldStart)
        assertEquals(100.0, waiting.transitionStart, 0.0)
        assertEquals(110.0, waiting.transitionEnd, 0.0)
        assertEquals(8.0, waiting.fadeSeconds, 0.0)
        assertEquals(12.0, waiting.incomingCueTime, 0.0)
        assertEquals(1.25, waiting.outgoingPlaybackRate, 0.0)
        assertEquals(0.9, waiting.incomingPlaybackRate, 0.0)
        assertEquals(TransitionStyle.DJ_FILTER, waiting.transitionStyle)

        // Five outgoing source seconds at 1.25x are four wall seconds: exactly half the mix.
        val late = plan.forLivePlayback(105.0)
        assertTrue(late.shouldStart)
        assertEquals(0.5, late.initialProgress, 1e-9)
        assertEquals(4.0, late.fadeSeconds, 1e-9)
        assertEquals(15.6, late.incomingCueTime, 1e-9)
        assertEquals(selected, late.nativePlan)
    }

    @Test fun `missed selected window falls back without inventing another plan`() {
        val source = mobilePlan(desktopCases().first().getJSONObject("input"))
        val selected = checkNotNull(source.nativePlan).copy(
            transitionStart = 100.0,
            transitionEnd = 108.0,
        )
        val plan = source.copy(nativePlan = selected)

        val fallback = plan.forLivePlayback(107.96)
        assertNull(fallback.nativePlan)
        assertEquals(plan.transitionStart, fallback.transitionStart, 0.0)
        assertEquals(plan.transitionEnd, fallback.transitionEnd, 0.0)
        assertEquals(plan.incomingCueTime, fallback.incomingCueTime, 0.0)
        assertEquals(plan.reason, fallback.reason)
    }
}

internal fun desktopCases(): List<JSONObject> {
    val source = checkNotNull(TransitionPlannerTest::class.java.getResourceAsStream("/desktop-planner-fixtures.json"))
        .bufferedReader().use { it.readText() }
    val array = JSONArray(source)
    return List(array.length()) { array.getJSONObject(it) }
}

internal fun mobileAnalysis(value: JSONObject): TrackAnalysis {
    val features = TrackFeatures.parse(value)
    return TrackAnalysis(
        status = value.optString("status"), trackId = value.optString("trackId"),
        duration = features.duration, bpm = features.bpm, beatInterval = features.beatInterval,
        beatConfidence = features.beatConfidence, downbeats = features.downbeats,
        phraseBoundaries = features.phraseBoundaries, firstBeat = features.firstBeat,
        key = features.key, keyConfidence = features.keyConfidence,
        audibleStartTime = features.audibleStartTime, pickupTime = features.pickupTime,
        introEndTime = features.introEndTime, contentEndTime = features.contentEndTime,
        outroStartTime = features.outroStartTime, mixInTime = features.mixInTime, mixOutTime = features.mixOutTime,
        energyCurve = features.energyCurve, lowEnergyCurve = features.lowEnergyCurve,
        vocalActivityMask = features.vocalActivityMask, vocalProbability = features.vocalProbability,
        mixInCandidates = features.mixInCandidates, mixOutCandidates = features.mixOutCandidates,
        plannerFeaturesJson = features.plannerFeaturesJson,
    )
}

internal fun mobilePlan(input: JSONObject): TransitionPlan {
    fun track(key: String): Track = input.getJSONObject(key).let {
        Track(id = it.getString("id"), title = it.getString("title"), artist = it.getString("artist"),
            album = it.getString("album"), albumId = it.getString("albumId"),
            durationMs = (it.getDouble("durationSeconds") * 1000).toLong())
    }
    return planTransition(mobileAnalysis(input.getJSONObject("analysis")), mobileAnalysis(input.getJSONObject("nextAnalysis")),
        currentTrack = track("currentTrack"), nextTrack = track("nextTrack"),
        currentTime = input.getDouble("currentTime"), duration = input.getDouble("duration"),
        fadeSeconds = input.getDouble("fadeSeconds"), minFadeSeconds = input.getDouble("minFadeSeconds"),
        mode = if (input.getString("mode") == "smart") CrossfadeMode.SMART else CrossfadeMode.STANDARD,
        albumSequential = input.optBoolean("albumSequential"))
}

internal fun assertJson(expected: Any?, actual: Any?, path: String) {
    when (expected) {
        is JSONObject -> {
            assertTrue("$path should be an object", actual is JSONObject)
            actual as JSONObject
            assertEquals(path, expected.keys().asSequence().toSet(), actual.keys().asSequence().toSet())
            expected.keys().forEach { key -> assertJson(expected.get(key), actual.get(key), "$path.$key") }
        }
        is JSONArray -> {
            assertTrue("$path should be an array", actual is JSONArray)
            actual as JSONArray
            assertEquals(path, expected.length(), actual.length())
            repeat(expected.length()) { assertJson(expected.get(it), actual.get(it), "$path[$it]") }
        }
        is Number -> {
            assertTrue("$path should be numeric", actual is Number)
            assertEquals(path, expected.toDouble(), (actual as Number).toDouble(), 1e-9)
        }
        else -> assertEquals(path, expected, actual)
    }
}
